### ISSUE TITLE
Calibration unsuccessful!

### ISSUE THREAD

**Issue by cuttlefish-ball** [JARVIS-MoCap/JARVIS-AnnotationTool#4]
When I try to calibrate the extrinsics  of the example recording as the website said, it became unsuccessful and  gave a hint that "camera pairs [camera_t, camera_ltf]: found only 0 valid checkerboards, aborting calibration. Make sure your checkerboard parameters are set correct. "  However, I do not change any parameters and make it untouched and the parameters are correct.

![`5A`I{F65C8PT5%M9CD7Z_F](https://user-images.githubusercontent.com/97815126/184465600-b17a98f6-b8e2-4f49-88ca-463f787e9421.jpg)

**Comment by JARVIS-MoCap** [comment]
Hi,

thanks for letting me know! Can you try installing the latest version from [here](https://github.com/JARVIS-MoCap/JARVIS-AnnotationTool/releases/tag/v1.2) and check if calibration is still unsuccessful?
 There was a bug that made the Standard calibration use the ChArUco Detector in some cases, I think this is most likely what's causing the calibration to fail in your case.

Best,
Timo
