### ISSUE TITLE
Generating Calibration Board

### ISSUE THREAD

**Issue by KenR22** [JARVIS-MoCap/JARVIS-AnnotationTool#5]
Hi I am trying to generate calibration board from this site: https://markrmakr.herokuapp.com/charuco_board
However, on the annotation toolbox there is a parameter called side length. I was wondering what that would correspond to if I use a board from the website mentioned.

Also do you know of any better option for generating charuco boards?

Thanks

**Comment by timohueser** [comment]
Hi! 
The side length is the length of a single checkerboard square (e.g. one of the black ones) in millimeters. In the calibration board generator you linked I'm assuming this is the 'Length of a black square in [mm]' parameter. I would suggest to print out the board and measure the length on the final printed board to make sure the length you're entering into the AnnotationTool is accurate.

I usually recommend [calib.io](https://calib.io/pages/camera-calibration-pattern-generator), but I don't think it's better or worse than the website you're using.

Timo

**Comment by KenR22** [comment]
I actually started with Calib io but I got a bit confused about the dictionary argument in the Jarvis as Calib io does not offer the argument. i.e. 4x4_1000(could not find the where I would input the 1000)

Thanks again.
