### ISSUE TITLE
Calibration Stuck at 99%

### ISSUE THREAD

**Issue by KenR22** [JARVIS-MoCap/JARVIS-AnnotationTool#6]
Hi,

When I run the calibration, the extrinsic calibration seems to be stuck at 99%. If I close the calibration then it seems to save the YAML file but they do not seem to be right.
![image](https://user-images.githubusercontent.com/11378468/187470805-eb2381df-09dc-4759-b7e7-f042d4b706aa.png)

Here is an example YAML that was saved:
%YAML:1.0
---
intrinsicMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 5.0108589414539790e+02, 0., 0., 0., 5.0217136123022357e+02,
       0., 3.1740749857840819e+02, 1.8371580711700071e+02, 1. ]
distortionCoefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 1.1327725023237396e-01, -2.4446001902304867e-01, 0., 0., 0. ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0., 0., 0. ]

Thanks

**Comment by KenR22** [comment]
Also, I would like to note that I am using cameras with different pixel resolutions for our setup(640p and 1080p)

**Comment by KenR22** [comment]
I think I got it solved. The issue might have been there because some of the projections did not have the primary cameras.

**Comment by EmaJugovic** [comment]
Hello, I am having the same issue. I attached a screenshot of the error and a rough schematic of the camera layout. I am using camera D as my primary camera and all calibration videos are made in relation to cam D. 

Do you perhaps know what the issue could be? Thanks in advance!

![IMG_1470](https://github.com/user-attachments/assets/7ed829c1-2dd8-4226-b3c2-39c503410221)

![unnamed](https://github.com/user-attachments/assets/5670bba4-9f67-4444-88d2-0786bc847560)
